repos:
-   repo: https://github.com/zricethezav/gitleaks
    rev: v7.5.0
    hooks:
    -   id: gitleaks
-   repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
    - id: black
      args:
          - --line-length=120
      language_version: python3.8
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.1
    hooks:
    - id: flake8
      args:
          - --max-line-length=120
