services:
  - type: worker
    name: app
    region: frankfurt
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot/main.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
